import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val appcompat: String = "androidx.appcompat:appcompat:_"

    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    const val core_ktx: String = "androidx.core:core-ktx:_"

    const val lifecycle_common_java8: String = "androidx.lifecycle:lifecycle-common-java8:_"

    const val lifecycle_process: String = "androidx.lifecycle:lifecycle-process:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:_"

    const val contour: String = "app.cash.contour:contour:_"

    const val atrium_fluent_en_gb: String = "ch.tutteli.atrium:atrium-fluent-en_GB:_"

    const val aapt2: String = "com.android.tools.build:aapt2:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    const val apollo_coroutines_support: String =
            "com.apollographql.apollo:apollo-coroutines-support:_"

    const val apollo_runtime: String = "com.apollographql.apollo:apollo-runtime:_"

    const val com_apollographql_apollo_gradle_plugin: String =
            "com.apollographql.apollo:com.apollographql.apollo.gradle.plugin:_"

    const val klaxon: String = "com.beust:klaxon:_"

    const val clikt: String = "com.github.ajalt.clikt:clikt:_"

    const val mordant: String = "com.github.ajalt:mordant:_"

    const val com_github_ben_manes_versions_gradle_plugin: String =
            "com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:_"

    const val fuel: String = "com.github.kittinunf.fuel:fuel:_"

    const val fuel_kotlinx_serialization: String =
            "com.github.kittinunf.fuel:fuel-kotlinx-serialization:_"

    const val material: String = "com.google.android.material:material:_"

    const val dagger: String = "com.google.dagger:dagger:_"

    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:_"

    const val h2: String = "com.h2database:h2:_"

    const val picnic: String = "com.jakewharton.picnic:picnic:_"

    const val retrofit2_kotlinx_serialization_converter: String =
            "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:_"

    const val mockito_kotlin: String = "com.nhaarman.mockitokotlin2:mockito-kotlin:_"

    const val hoplite_core: String = "com.sksamuel.hoplite:hoplite-core:_"

    const val hoplite_hocon: String = "com.sksamuel.hoplite:hoplite-hocon:_"

    const val hoplite_yaml: String = "com.sksamuel.hoplite:hoplite-yaml:_"

    const val moshi: String = "com.squareup.moshi:moshi:_"

    const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:_"

    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    const val mockwebserver: String = "com.squareup.okhttp3:mockwebserver:_"

    const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    const val okio: String = "com.squareup.okio:okio:_"

    const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:_"

    const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    const val com_squareup_sqldelight_gradle_plugin: String =
            "com.squareup.sqldelight:com.squareup.sqldelight.gradle.plugin:_"

    const val runtime_jvm: String = "com.squareup.sqldelight:runtime-jvm:_"

    const val sqlite_driver: String = "com.squareup.sqldelight:sqlite-driver:_"

    const val kotlinpoet: String = "com.squareup:kotlinpoet:_"

    const val statemachine: String = "com.tinder.statemachine:statemachine:_"

    const val konf: String = "com.uchuhimo:konf:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val arrow_core: String = "io.arrow-kt:arrow-core:_"

    const val konad: String = "io.github.lucapiccinelli:konad:_"

    const val kotlin_faker: String = "io.github.serpro69:kotlin-faker:_"

    const val kotest_assertions_arrow: String = "io.kotest:kotest-assertions-arrow:_"

    const val kotest_assertions_core: String = "io.kotest:kotest-assertions-core:_"

    const val kotest_assertions_json: String = "io.kotest:kotest-assertions-json:_"

    const val kotest_property: String = "io.kotest:kotest-property:_"

    const val kotest_runner_junit5: String = "io.kotest:kotest-runner-junit5:_"

    const val ktor_client_core: String = "io.ktor:ktor-client-core:_"

    const val ktor_client_okhttp: String = "io.ktor:ktor-client-okhttp:_"

    const val ktor_client_serialization: String = "io.ktor:ktor-client-serialization:_"

    const val mockk: String = "io.mockk:mockk:_"

    const val mockk_common: String = "io.mockk:mockk-common:_"

    const val strikt_arrow: String = "io.strikt:strikt-arrow:_"

    const val strikt_core: String = "io.strikt:strikt-core:_"

    const val skrapeit_core: String = "it.skrape:skrapeit-core:_"

    const val skrapeit_http_fetcher: String = "it.skrape:skrapeit-http-fetcher:_"

    const val junit_junit: String = "junit:junit:_"

    const val kluent: String = "org.amshove.kluent:kluent:_"

    const val exposed_core: String = "org.jetbrains.exposed:exposed-core:_"

    const val exposed_dao: String = "org.jetbrains.exposed:exposed-dao:_"

    const val exposed_java_time: String = "org.jetbrains.exposed:exposed-java-time:_"

    const val exposed_jdbc: String = "org.jetbrains.exposed:exposed-jdbc:_"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:_"

    const val org_jetbrains_kotlin_plugin_serialization_gradle_plugin: String =
            "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin:_"

    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:_"

    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    const val kotlin_serialization: String = "org.jetbrains.kotlin:kotlin-serialization:_"

    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    const val kotlinx_collections_immutable: String =
            "org.jetbrains.kotlinx:kotlinx-collections-immutable:_"

    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    const val kotlinx_datetime: String = "org.jetbrains.kotlinx:kotlinx-datetime:_"

    const val kotlinx_html_jvm: String = "org.jetbrains.kotlinx:kotlinx-html-jvm:_"

    const val kotlinx_serialization_core: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-core:_"

    const val kotlinx_serialization_json: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-json:_"

    const val kotlinx_serialization_properties: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-properties:_"

    const val markdown_jvm: String = "org.jetbrains:markdown-jvm:_"

    const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:_"

    const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:_"

    const val kodein_db_jvm: String = "org.kodein.db:kodein-db-jvm:_"

    const val kodein_db_serializer_kotlinx: String = "org.kodein.db:kodein-db-serializer-kotlinx:_"

    const val kodein_leveldb_jni_jvm_linux: String = "org.kodein.db:kodein-leveldb-jni-jvm-linux:_"

    const val kodein_leveldb_jni_jvm_macos: String = "org.kodein.db:kodein-leveldb-jni-jvm-macos:_"

    const val kodein_leveldb_jni_jvm_windows: String =
            "org.kodein.db:kodein-leveldb-jni-jvm-windows:_"

    const val kodein_di: String = "org.kodein.di:kodein-di:_"

    const val koin_core: String = "org.koin:koin-core:_"

    const val mockito_core: String = "org.mockito:mockito-core:_"

    const val mockito_junit_jupiter: String = "org.mockito:mockito-junit-jupiter:_"

    const val kotlin_statistics: String = "org.nield:kotlin-statistics:_"

    const val spek_dsl_jvm: String = "org.spekframework.spek2:spek-dsl-jvm:_"

    const val spek_runner_junit5: String = "org.spekframework.spek2:spek-runner-junit5:_"

    const val spek_runtime_jvm: String = "org.spekframework.spek2:spek-runtime-jvm:_"

    const val source_api: String = "org.tachiyomi:source-api:_"
}
