# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: runOnGitHub
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - id: buildscan
        name: Add Build Scan URLs to Pull Request
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Buildscan url for run [${{ github.run_id }}](https://github.com/LouisCAD/kotlin-libraries-playground/issues/runs/${{ github.run_id }})
            ${{ steps.gradle.outputs.build-scan-url }}
      - id: artifact
        name: Add build scan to the artifact
        uses: actions/upload-artifact@v2
        with:
          name: buildscan-assemble
          path: 'buildscan.log'
